name: Go

on:
  push:
    branches:
      - 'main'
  pull_request:
    branches:
      - 'main'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      id: setup
      uses: actions/setup-go@v4
      with:
        go-version-file: 'go.mod'
        cache: false

    - uses: kenchan0130/actions-system-info@v1.3.0
      id: system-info

    - name: Go paths
      id: go-cache-paths
      shell: sh
      run: |
        echo "go-cache-dir=$(go env GOCACHE)" >> $GITHUB_OUTPUT
        echo "go-mod-cache-dir=$(go env GOMODCACHE)" >> $GITHUB_OUTPUT

    - name: Cache key
      id: key
      shell: sh
      run: |
        echo "key"=$(cat go.sum | md5sum | cut -d\  -f1) >> $GITHUB_OUTPUT

    - name: Go Build Cache
      id: build-cache
      uses: actions/cache@v4
      with:
        path: ${{ steps.go-cache-paths.outputs.go-cache-dir }}
        key: go-build-${{ runner.os }}-${{ runner.arch }}-${{ steps.system-info.outputs.release }}-${{ steps.setup.outputs.go-version }}-${{ steps.key.outputs.key }}
        restore-keys: |
          go-build-${{ runner.os }}-${{ runner.arch }}-${{ steps.system-info.outputs.release }}-${{ steps.setup.outputs.go-version }}
          go-build-${{ runner.os }}-${{ runner.arch }}-${{ steps.system-info.outputs.release }}
          go-build-${{ runner.os }}-${{ runner.arch }}

    - name: Go Mod Cache
      id: mod-cache
      uses: actions/cache@v4
      with:
        path: ${{ steps.go-cache-paths.outputs.go-mod-cache-dir }}
        key: go-mod-${{ runner.os }}-${{ runner.arch }}-${{ steps.system-info.outputs.release }}-${{ steps.setup.outputs.go-version }}-${{ steps.key.outputs.key }}
        restore-keys: |
          go-mod-${{ runner.os }}-${{ runner.arch }}-${{ steps.system-info.outputs.release }}-${{ steps.setup.outputs.go-version }}
          go-mod-${{ runner.os }}-${{ runner.arch }}-${{ steps.system-info.outputs.release }}
          go-mod-${{ runner.os }}-${{ runner.arch }}

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...

