name: Go

on:
  push:
    branches:
      - 'main'
  pull_request:
    branches:
      - 'main'

jobs:
  Test:
    runs-on: ubuntu-latest
    permissions:
      # Required: allow read access to the content for analysis.
      contents: read
      # Optional: allow read access to pull request. Use with `only-new-issues` option.
      pull-requests: read
      # Optional: allow write access to checks to allow the action to annotate code in the PR.
      checks: write

    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      id: setup
      uses: actions/setup-go@v4
      with:
        go-version-file: 'go.mod'
        cache: false

    - uses: kenchan0130/actions-system-info@v1.3.0
      id: system-info

    - name: Go paths
      id: go-cache-paths
      shell: sh
      run: |
        echo "go-cache-dir=$(go env GOCACHE)" >> $GITHUB_OUTPUT
        echo "go-mod-cache-dir=$(go env GOMODCACHE)" >> $GITHUB_OUTPUT

    - name: Cache key
      id: key
      shell: sh
      run: |
        echo "key"=$(cat go.sum | md5sum | cut -d\  -f1) >> $GITHUB_OUTPUT

    - name: Go Build Cache
      uses: actions/cache@v4
      with:
        path: |
          ${{ steps.go-cache-paths.outputs.go-cache-dir }}
          ${{ steps.go-cache-paths.outputs.go-mod-cache-dir }}
        key: go-build-${{ runner.os }}-${{ runner.arch }}-${{ steps.system-info.outputs.release }}-go-${{ steps.setup.outputs.go-version }}-${{ steps.key.outputs.key }}
        restore-keys: |
          go-build-${{ runner.os }}-${{ runner.arch }}-${{ steps.system-info.outputs.release }}-go-${{ steps.setup.outputs.go-version }}
          go-build-${{ runner.os }}-${{ runner.arch }}-${{ steps.system-info.outputs.release }}
          go-build-${{ runner.os }}-${{ runner.arch }}

    - name: Ensure tidy
      run: go mod tidy -diff

    - name: Build
      run: go build ./...

    - name: Test
      run: go test -v ./...

    - name: golangci-lint
      uses: golangci/golangci-lint-action@v6
      with:
        only-new-issues: true

    - name: Run Gosec Security Scanner
      uses: securego/gosec@master
      with:
        args: -exclude=G404 ./...
